# Generated by Django 4.0.6 on 2022-07-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_info',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
