# Generated by Django 4.0.6 on 2022-07-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_book_info_remove_book_library_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_info',
            field=models.TextField(null=True),
        ),
    ]
