# Generated by Django 4.0.5 on 2022-07-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_comment_email_rename_book_comment_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isbn',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user',
        ),
    ]
