# Generated by Django 4.0.5 on 2022-07-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_isbn_comment_book_rename_email_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='isbn',
        ),
    ]
